namespace NanaZip.Modern
{
    [default_interface]
    runtimeclass CopyPage : Windows.UI.Xaml.Controls.Page
    {
        CopyPage();

        String TitleText;
        String PathLabelText;
        String PathText;

        event Windows.Foundation.TypedEventHandler<CopyPage, Object> OkButtonClicked;
        event Windows.Foundation.TypedEventHandler<CopyPage, Object> CancelButtonClicked;

        static Windows.UI.Xaml.DependencyProperty TitleTextProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty PathLabelTextProperty{ get; };
        static Windows.UI.Xaml.DependencyProperty PathTextProperty{ get; };
    }
}
