namespace NanaZip.Modern
{
    [default_interface]
    runtimeclass InformationPage : Windows.UI.Xaml.Controls.Page
    {
        String Text;

        static Windows.UI.Xaml.DependencyProperty TextProperty{ get; };
    }
}
