name: Feature request
description: Request a new feature into NanaZip.
labels: ["enhancements"]
body:
  - type: textarea
    label: Describe the feature
  - type: checkboxes
    attributes:
      options:
        - label: I have confirmed that this feature isn't yet implemented in the latest Preview release.
          required: true
