#define MY_VER_MAJOR 1
#define MY_VER_MINOR 0
#define MY_VER_BUILD 11
#define MY_VERSION_NUMBERS "1.0 Canary (Build 11)"
#define MY_VERSION MY_VERSION_NUMBERS

#ifdef MY_CPU_NAME
  #define MY_VERSION_CPU MY_VERSION " (" MY_CPU_NAME ")"
#else
  #define MY_VERSION_CPU MY_VERSION
#endif

#define MY_DATE "2021-09-11"
#undef MY_COPYRIGHT
#undef MY_VERSION_COPYRIGHT_DATE
#define MY_AUTHOR_NAME "M2-Team"
#define MY_COPYRIGHT "Copyright (c) M2-Team and Contributors"

#define MY_COPYRIGHT_DATE MY_COPYRIGHT " : " MY_DATE
#define MY_VERSION_COPYRIGHT_DATE MY_VERSION_CPU " : " MY_COPYRIGHT " : " MY_DATE
