name: Build Binaries

on:
  push:
    paths-ignore:
      - "Documents/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "Documents/**"
      - "**/*.md"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
        sanitizers: [false, true]
        exclude:
          - configuration: Debug
            sanitizers: true
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      ARTIFACT_SUFFIX: ${{ matrix.configuration }}_${{ matrix.platform }}${{ matrix.sanitizers && '_ASAN' || '' }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: "recursive"
      - uses: microsoft/setup-msbuild@v3
      - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
        run: dotnet nuget locals all --clear
      - name: Build
        run: |
          MSBuild -binaryLogger:Output\BuildAllTargets_${{ env.ARTIFACT_SUFFIX }}.binlog `
            -m `
            -p:Configuration=${{ matrix.configuration }} `
            -p:Platform=${{ matrix.platform }} `
            -p:NanaZipBuildWithSanitizers=${{ matrix.sanitizers }} `
            -p:AppxBundlePlatforms=${{ matrix.platform }} `
            BuildAllTargets.proj
      - name: Upload MSIX Bundle
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_ApplicationPackages_${{ env.ARTIFACT_SUFFIX }}
          path: Output/Binaries/AppPackages
      - name: Upload Extension Package Installer
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_ExtensionPackageInstaller_${{ env.ARTIFACT_SUFFIX }}
          path: Output/NanaZip.ExtensionPackage_*.exe
      - name: Upload MSBuild Build Process Binary Log
        uses: actions/upload-artifact@v7.0.1
        if: "!cancelled()"
        with:
          name: NanaZip_Mainline_BuildBinaryLog_${{ env.ARTIFACT_SUFFIX }}
          path: Output/BuildAllTargets_${{ env.ARTIFACT_SUFFIX }}.binlog
      - name: Upload Portable Binaries
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_PortableBinaries_${{ env.ARTIFACT_SUFFIX }}
          path: Output/Binaries/Root/Binaries
      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_DebugSymbols_${{ env.ARTIFACT_SUFFIX }}
          path: Output/Binaries/Root/Symbols
  test:
    runs-on: ${{ matrix.platform == 'ARM64' && 'windows-11-arm' || 'windows-latest' }}
    needs:
      - build
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
        sanitizers: [false, true]
        exclude:
          - configuration: Debug
            sanitizers: true
    env:
      ARTIFACT_SUFFIX: ${{ matrix.configuration }}_${{ matrix.platform }}${{ matrix.sanitizers && '_ASAN' || '' }}
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          repository: M2Team/K7Tests
      - uses: actions/download-artifact@v8.0.1
        with:
          name: NanaZip_Mainline_PortableBinaries_${{ env.ARTIFACT_SUFFIX }}
          path: NanaZip_Mainline_PortableBinaries_${{ env.ARTIFACT_SUFFIX }}
      - run: Install-Module -Name Pester -Scope CurrentUser -MinimumVersion 5.0.0 -Force
      - run: |
          .\run.ps1 `
            -Program .\NanaZip_Mainline_PortableBinaries_${{ env.ARTIFACT_SUFFIX }}\NanaZip.Universal.Console.exe `
            -Verbosity Detailed `
            -Verbose
