name: Build Binaries

on:
  push:
    paths-ignore:
      - "Documents/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "Documents/**"
      - "**/*.md"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: "recursive"
      - uses: microsoft/setup-msbuild@v3
      - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
        run: dotnet nuget locals all --clear
      - name: Build
        run: MSBuild -binaryLogger:Output\BuildAllTargets_${{ matrix.configuration }}_${{ matrix.platform }}.binlog -m -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} BuildAllTargets.proj
      - name: Upload MSIX Bundle
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_ApplicationPackages_${{ matrix.configuration }}_${{ matrix.platform }}
          path: Output/Binaries/AppPackages
      - name: Upload Extension Package Installer
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_ExtensionPackageInstaller_${{ matrix.configuration }}_${{ matrix.platform }}
          path: Output/NanaZip.ExtensionPackage_*.exe
      - name: Upload MSBuild Build Process Binary Log
        uses: actions/upload-artifact@v7.0.1
        if: "!cancelled()"
        with:
          name: NanaZip_Mainline_BuildBinaryLog_${{ matrix.configuration }}_${{ matrix.platform }}
          path: Output/BuildAllTargets_${{ matrix.configuration }}_${{ matrix.platform }}.binlog
      - name: Upload Portable Binaries
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_PortableBinaries_${{ matrix.configuration }}_${{ matrix.platform }}
          path: Output/Binaries/Root/Binaries
      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_DebugSymbols_${{ matrix.configuration }}_${{ matrix.platform }}
          path: Output/Binaries/Root/Symbols
  test:
    runs-on: ${{ matrix.runner }}
    needs:
      - build
    strategy:
      matrix:
        include:
          - configuration: Debug
            platform: x64
            runner: windows-latest
          - configuration: Debug
            platform: ARM64
            runner: windows-11-arm
          - configuration: Release
            platform: x64
            runner: windows-latest
          - configuration: Release
            platform: ARM64
            runner: windows-11-arm
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          repository: M2Team/K7Tests
      - uses: actions/download-artifact@v8.0.1
        with:
          name: NanaZip_Mainline_PortableBinaries_${{ matrix.configuration }}_${{ matrix.platform }}
          path: NanaZip_Mainline_PortableBinaries
      - run: Install-Module -Name Pester -Scope CurrentUser -MinimumVersion 5.0.0 -Force
      - run: |
          .\run.ps1 `
            -Program .\NanaZip_Mainline_PortableBinaries\NanaZip.Universal.Console.exe `
            -Verbosity Detailed `
            -Verbose
