name: Build Binaries

on:
  push:
    paths-ignore:
      - 'Documents/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'Documents/**'
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: 'recursive'
      - uses: microsoft/setup-msbuild@v3
      - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
        run: dotnet nuget locals all --clear
      - name: Build
        run: MSBuild -binaryLogger:Output\BuildAllTargets.binlog -m BuildAllTargets.proj
      - name: Upload MSIX Bundle
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_ApplicationPackages
          path: Output/Binaries/AppPackages
      - name: Upload Extension Package Installer
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_ExtensionPackageInstaller
          path: Output/NanaZip.ExtensionPackage_*.exe
      - name: Upload MSBuild Build Process Binary Log
        uses: actions/upload-artifact@v7.0.1
        if: "!cancelled()"
        with:
          name: NanaZip_Mainline_BuildBinaryLog
          path: Output/BuildAllTargets.binlog
      - name: Upload Portable Binaries
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_PortableBinaries
          path: Output/Binaries/Root/Binaries
      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NanaZip_Mainline_DebugSymbols
          path: Output/Binaries/Root/Symbols
  test:
    runs-on: windows-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          repository: M2Team/K7Tests
      - uses: actions/download-artifact@v8.0.1
        name: NanaZip_Mainline_PortableBinaries
      - run: Install-Module -Name Pester -Scope CurrentUser -MinimumVersion 5.0.0 -Force
      - run: |
          .\run.ps1 `
            -Program .\NanaZip_Mainline_PortableBinaries\x64\NanaZip.Universal.Console.exe `
            -Verbosity Detailed `
            -Verbose
